services:
###############################################################################
# 1 ▸ Redis  (internal, free plan, no auth)
###############################################################################
- type: redis
  name: pdf-redis
  plan: free
  maxmemoryPolicy: allkeys-lru        # reasonable default
  enableInternalAuth: false           # 🔑 TURN OFF password
  ipAllowList: []                     # empty → only Render services (same account/region)

###############################################################################
# 2 ▸ Spring-Boot back-end (API)
###############################################################################
- type: web
  name: pdf-chatbot-api
  runtime: docker
  autoDeploy: true

  envVars:
    # ── OpenAI secret ───────────────────────────────────────────────────────
    - key: OPENAI_API_KEY
      sync: false                      # add the value in the dashboard

    # ── Redis (internal host & port, no password) ──────────────────────────
    - key: REDIS_HOST
      fromService:
        type: redis
        name: pdf-redis
        property: host                # ⇒ "pdf-redis"
    - key: REDIS_PORT
      fromService:
        type: redis
        name: pdf-redis
        property: port                # ⇒ "6379"

###############################################################################
# 3 ▸ React front-end (static site)  ── OPTIONAL
###############################################################################
- type: web
  name: pdf-chat-ui
  runtime: static
  buildCommand: cd pdf-chat-ui && npm ci && npm run build
  staticPublishPath: pdf-chat-ui/build
  pullRequestPreviewsEnabled: false

  # Expose the API host:port to React if needed
  envVars:
    - key: REACT_APP_API_HOSTPORT
      fromService:
        type: web
        name: pdf-chatbot-api
        property: hostport            # e.g. "pdf-chatbot-api:8080"
