services:
###############################################################################
# 1 ▸ PostgreSQL (internal)
###############################################################################
- type: psql
  name: pdf-chat-db
  plan: free

###############################################################################
# 2 ▸ Spring Boot API
###############################################################################
- type: web
  name: pdf-chatbot-api
  runtime: docker
  autoDeploy: true

  envVars:
    - key: OPENAI_API_KEY
      sync: false

    # PostgreSQL connection
    - key: SPRING_DATASOURCE_URL
      fromDatabase:
        name: pdf-chat-db
        property: connectionString

    - key: SPRING_DATASOURCE_USERNAME
      fromDatabase:
        name: pdf-chat-db
        property: user

    - key: SPRING_DATASOURCE_PASSWORD
      fromDatabase:
        name: pdf-chat-db
        property: password

###############################################################################
# 3 ▸ React UI
###############################################################################
- type: web
  name: pdf-chat-ui
  runtime: static
  buildCommand: cd pdf-chat-ui && npm ci && npm run build
  staticPublishPath: pdf-chat-ui/build

  envVars:
    - key: REACT_APP_API_HOSTPORT
      fromService:
        type: web
        name: pdf-chatbot-api
        property: hostport
