services:
###############################################################################
# 1 ▸ Redis  (internal, free plan)
###############################################################################
- type: redis
  name: pdf-redis
  plan: free
  maxmemoryPolicy: allkeys-lru   # reasonable default
  enableInternalAuth: false 
  ipAllowList: []    

###############################################################################
# 2 ▸ Spring-Boot back-end  (API)
###############################################################################
- type: web
  name: pdf-chatbot-api
  runtime: docker
  autoDeploy: true

  envVars:
    ############################################
    # OpenAI secret  (add value once in the UI)
    ############################################
    - key: OPENAI_API_KEY
      sync: false                # you’ll paste the real key in the dashboard

    ############################################
    # Redis connection  (single URL is easiest)
    ############################################
	- key: REDIS_HOST
	  fromService: { type: redis, name: pdf-redis, property: host }
	- key: REDIS_PORT
	  fromService: { type: redis, name: pdf-redis, property: port }


###############################################################################
# 3 ▸ React front-end  (static site)  ── OPTIONAL
###############################################################################
- type: web
  name: pdf-chat-ui
  runtime: static
  buildCommand: cd pdf-chat-ui && npm ci && npm run build
  staticPublishPath: pdf-chat-ui/build
  pullRequestPreviewsEnabled: false

  # If your React code needs to know the API origin you can expose HOSTPORT:
  # REACT_APP_API_HOSTPORT → "pdf-chatbot-api:8080"
  envVars:
    - key: REACT_APP_API_HOSTPORT
      fromService:
        type: web
        name: pdf-chatbot-api
        property: hostport         # allowed: host | hostport | port
