services:
  ##############################################################
  # 1 ▸ Redis (internal - free plan)
  ##############################################################
  - type: redis
    name: pdf-redis           # will become “pdf-redis:6379”
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []           # empty ⇒ only other Render services may connect

  ##############################################################
  # 2 ▸ Spring-Boot Backend  (root of repo)
  ##############################################################
  - type: web
    name: pdf-chatbot-api
    runtime: java
    repoPath: .               # backend lives in repo root
    buildCommand: ./mvnw -ntp package -DskipTests
    startCommand: >
      java -jar target/*SNAPSHOT.jar
    autoDeploy: true

    envVars:
      ########################################
      # OpenAI secret – set once in dashboard
      ########################################
      - key: OPENAI_API_KEY
        sync: false           # you’ll add the value in Render UI

      ########################################
      # Redis connection pieces
      ########################################
      - key: REDIS_HOST
        fromService:
          type: redis
          name: pdf-redis
          property: host

      - key: REDIS_PORT
        fromService:
          type: redis
          name: pdf-redis
          property: port

      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: pdf-redis
          property: password   # ← valid property

      # ↓ Spring Boot 3.x prefers a single URL
      - key: SPRING_REDIS_URL
        value: "redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"
      # if you still use spring.redis.* keys, keep them in application.properties

  ##############################################################
  # 3 ▸ React Front-end  (optional – delete block if staying on Vercel)
  ##############################################################
  - type: web
    name: pdf-chat-ui
    runtime: static           # Render’s “Static Site”
    repoPath: pdf-chat-ui     # directory containing package.json
    buildCommand: npm ci && npm run build
    staticPublishPath: build  # where CRA/Vite/Next exports pre-built files
    pullRequestPreviewsEnabled: false

    envVars:
      # Front-end needs to know backend base URL
      - key: REACT_APP_API_BASE
        fromService:
          type: web
          name: pdf-chatbot-api
          property: url
