################################################################################
# render.yaml  ▸  one database  +  two services
################################################################################

################################ 1 ▸ DATABASE ##################################
databases:
  - name: pdf-chat-db          # Render will create a Postgres instance
    plan: free                 # 90-day free tier

################################ 2 ▸ SPRING-BOOT API ###########################
services:
###############################################################################
###############################################################################
# 2 ▸ Spring Boot API
###############################################################################
- type: web
  name: pdf-chatbot-api
  runtime: docker
  autoDeploy: true

  envVars:
    - key: OPENAI_API_KEY
      sync: false

    # PostgreSQL connection
    - key: SPRING_DATASOURCE_URL
      fromDatabase:
        name: pdf-chat-db
        property: jdbcConnectionString

    - key: SPRING_DATASOURCE_USERNAME
      fromDatabase:
        name: pdf-chat-db
        property: user

    - key: SPRING_DATASOURCE_PASSWORD
      fromDatabase:
        name: pdf-chat-db
        property: password

###############################################################################
# 3 ▸ React UI
###############################################################################
- type: web
  name: pdf-chat-ui
  runtime: static
  buildCommand: cd pdf-chat-ui && npm ci && npm run build
  staticPublishPath: pdf-chat-ui/build

  envVars:
    - key: REACT_APP_API_HOSTPORT
      fromService:
        type: web
        name: pdf-chatbot-api
        property: hostport
